//HPCC Systems KEL Compiler Version 1.6.0
IMPORT KEL16 AS KEL;
IMPORT CFG_Compile FROM PublicRecords_KEL.KEL_Queries_MAS_NonFCRA;
IMPORT * FROM KEL16.Null;
EXPORT L_Compile := MODULE
  SHARED Non_F_C_R_A_Phone_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout := RECORD
    KEL.typ.nstr P_I___Src_W_Inp_P_D_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_P_D_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_P_D_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_L_P_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_L_P_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_L_P_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_P_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_P_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_P_Last_Dt_List_Ev_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT Non_F_C_R_A_Phone_Summary_Attributes_V1_Dynamic_Res0_Layout := RECORDOF(__UNWRAP(DATASET([],Non_F_C_R_A_Phone_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout)));
  SHARED Non_F_C_R_A_S_S_N_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout_S_S_N_Summary_Source_List_Sorted_Layout := RECORD
    KEL.typ.nstr Primary_Name_Address_;
    KEL.typ.nstr Primary_Range_Address_;
    KEL.typ.nstr Zip_Address_;
    KEL.typ.nstr Translated_Source_Code_;
    KEL.typ.nstr Source_Date_First_Seen_;
    KEL.typ.nstr Source_Date_Last_Seen_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_S_S_N_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout := RECORD
    KEL.typ.nbool Exp1_;
    KEL.typ.nstr P___Inp_Cln_Phone_Home_;
    KEL.typ.ndataset(Non_F_C_R_A_S_S_N_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout_S_S_N_Summary_Source_List_Sorted_Layout) S_S_N_Summary_Source_List_Sorted_;
    KEL.typ.nstr P_I___Src_W_Inp_A_S_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_S_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_S_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_S_D_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_S_D_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_S_D_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_P_S_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_P_S_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_P_S_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_S_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_S_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_S_Last_Dt_List_Ev_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT Non_F_C_R_A_S_S_N_Summary_Attributes_V1_Dynamic_Res0_Layout := RECORDOF(__UNWRAP(DATASET([],Non_F_C_R_A_S_S_N_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout)));
  SHARED Non_F_C_R_A_Name_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout := RECORD
    KEL.typ.nstr P___Inp_Cln_Name_First_;
    KEL.typ.nstr P___Inp_Cln_Name_Last_;
    KEL.typ.nkdate P___Inp_Cln_D_O_B_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_D_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_D_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_D_Last_Dt_List_Ev_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT Non_F_C_R_A_Name_Summary_Attributes_V1_Dynamic_Res0_Layout := RECORDOF(__UNWRAP(DATASET([],Non_F_C_R_A_Name_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout)));
  SHARED Non_F_C_R_A_Address_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout := RECORD
    KEL.typ.nstr P_I___Src_W_Inp_F_L_A_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_A_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_F_L_A_Last_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_D_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_D_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_I___Src_W_Inp_A_D_Last_Dt_List_Ev_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT Non_F_C_R_A_Address_Summary_Attributes_V1_Dynamic_Res0_Layout := RECORDOF(__UNWRAP(DATASET([],Non_F_C_R_A_Address_Summary_Attributes_V1_Dynamic_Res0_Internal_Layout)));
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_P_L___Ast_Veh_Auto_Emrg_Dt_List_Ev_Layout := RECORD
    KEL.typ.ntyp(E_Vehicle().Typ) Automobile_;
    KEL.typ.nstr Vehicle_First_Seen_Date_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_P_L___Ast_Veh_Auto_Last_Dt_List_Ev_Layout := RECORD
    KEL.typ.ntyp(E_Vehicle().Typ) Automobile_;
    KEL.typ.nstr Vehicle_Last_Seen_Date_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Crim_List_Layout := RECORD
    KEL.typ.nstr Original_Filing_Date_;
    KEL.typ.nstr List_I_D_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Banko_List_Layout := RECORD
    KEL.typ.nstr Original_Filing_Date_;
    KEL.typ.nstr List_I_D_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Ln_J7_Y_List_Layout := RECORD
    KEL.typ.nstr Original_Filing_Date_;
    KEL.typ.nstr List_I_D_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_L_T_D7_Y_List_Layout := RECORD
    KEL.typ.nstr Original_Filing_Date_;
    KEL.typ.nstr List_I_D_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  SHARED Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout := RECORD
    KEL.typ.nuid Lex_I_D_;
    KEL.typ.str P___Lex_I_D_Seen_Flag_ := '';
    KEL.typ.nstr P___Lex_I_D_Category_;
    KEL.typ.str P___Lex_I_D_Is_Deceased_Flag_ := '';
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt_Ev_ := 0;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_P_L___Ast_Veh_Auto_Emrg_Dt_List_Ev_Layout) P_L___Ast_Veh_Auto_Emrg_Dt_List_Ev_;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_P_L___Ast_Veh_Auto_Last_Dt_List_Ev_Layout) P_L___Ast_Veh_Auto_Last_Dt_List_Ev_;
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt10_Y_ := 0;
    KEL.typ.int P_L___Ast_Veh_Auto_Cnt2_Y_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Auto_Emrg_Old_Dt_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Auto_Emrg_New_Msnc_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Auto_Emrg_Old_Msnc_Ev_;
    KEL.typ.int P_L___Ast_Veh_Air_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Air_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Air_Emrg_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Air_Emrg_Old_Dt_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Air_Emrg_New_Msnc_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Air_Emrg_Old_Msnc_Ev_;
    KEL.typ.int P_L___Ast_Veh_Wtr_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Veh_Wtr_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Wtr_Emrg_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Veh_Wtr_Emrg_Old_Dt_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Wtr_Emrg_New_Msnc_Ev_;
    KEL.typ.nint P_L___Ast_Veh_Wtr_Emrg_Old_Msnc_Ev_;
    KEL.typ.int P_L___Drg_Crim_Fel_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Crim_Fel_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Crim_Fel_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Fel_Old_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Fel_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Fel_Old_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Crim_Fel_New_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_Fel_Old_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_Fel_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Crim_Fel_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Crim_Nfel_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Crim_Nfel_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Crim_Nfel_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Nfel_Old_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Nfel_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Nfel_Old_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Crim_Nfel_New_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_Nfel_Old_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_Nfel_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Crim_Nfel_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Arst_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Arst_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Arst_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Arst_Old_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Arst_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Arst_Old_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Arst_New_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Arst_Old_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Arst_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Arst_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Crim_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Crim_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Crim_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Old_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Crim_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Old_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Crim_New_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_Old_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Crim_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Crim_Old_Msnc7_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Severity_Indx7_Y_;
    KEL.typ.nstr P_L___Drg_Crim_Behavior_Indx7_Y_;
    KEL.typ.int P_L___Drg_Bk_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Cnt10_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Bk_Dt_List1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Dt_List7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Dt_List10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Dt10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Old_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Old_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Old_Dt10_Y_;
    KEL.typ.nint P_L___Drg_Bk_New_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Bk_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Bk_New_Msnc10_Y_;
    KEL.typ.nint P_L___Drg_Bk_Old_Msnc1_Y_;
    KEL.typ.nint P_L___Drg_Bk_Old_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Bk_Old_Msnc10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Ch_List1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Ch_List7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Ch_List10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Ch_Type1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Ch_Type7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Ch_Type10_Y_;
    KEL.typ.int P_L___Drg_Bk_Ch7_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Ch7_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Ch7_Cnt10_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Ch13_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Ch13_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Ch13_Cnt10_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Dt10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Msnc1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Msnc7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Updt_New_Msnc10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Disp_List1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Disp_List7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Disp_List10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Type1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Type7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Type10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Dt1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Dt10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Msnc1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Msnc7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_New_Disp_Msnc10_Y_;
    KEL.typ.int P_L___Drg_Bk_Disp_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Disp_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Disp_Cnt10_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsms_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsms_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsms_Cnt10_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsch_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsch_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Bk_Dsch_Cnt10_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Bk_Type_List1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Type_List7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Type_List10_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Bus_Flag1_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Bus_Flag7_Y_;
    KEL.typ.nstr P_L___Drg_Bk_Bus_Flag10_Y_;
    KEL.typ.str P_L___Drg_Bk_Severity_Indx10_Y_ := '';
    KEL.typ.str P_L___Prof_Lic_Flag_Ev_ := '';
    KEL.typ.int P_L___Prof_Lic_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Prof_Lic_Issue_Dt_List_Ev_;
    KEL.typ.nstr P_L___Prof_Lic_Exp_Dt_List_Ev_;
    KEL.typ.nstr P_L___Prof_Lic_Indx_By_Lic_List_Ev_;
    KEL.typ.str P_L___Prof_Lic_Actv_Flag_ := '';
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Issue_Dt_;
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Exp_Dt_;
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Type_;
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Title_Type_;
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Indx_;
    KEL.typ.nstr P_L___Prof_Lic_Actv_New_Src_Type_;
    KEL.typ.str P_L___Curr_Addr_Full_ := '';
    KEL.typ.nstr P_L___Curr_Addr_Loc_I_D_;
    KEL.typ.str P_L___Prev_Addr_Full_ := '';
    KEL.typ.nstr P_L___Prev_Addr_Loc_I_D_;
    KEL.typ.str P_L___Curr_Addr_Cnty_ := '';
    KEL.typ.str P_L___Curr_Addr_Geo_ := '';
    KEL.typ.str P_L___Curr_Addr_Lat_ := '';
    KEL.typ.str P_L___Curr_Addr_Lng_ := '';
    KEL.typ.str P_L___Curr_Addr_Type_ := '';
    KEL.typ.str P_L___Curr_Addr_Status_ := '';
    KEL.typ.str P_L___Prev_Addr_Cnty_ := '';
    KEL.typ.str P_L___Prev_Addr_Geo_ := '';
    KEL.typ.str P_L___Prev_Addr_Lat_ := '';
    KEL.typ.str P_L___Prev_Addr_Lng_ := '';
    KEL.typ.str P_L___Prev_Addr_Type_ := '';
    KEL.typ.str P_L___Prev_Addr_Status_ := '';
    KEL.typ.int P_L___Curr_Addr_Is_Vacant_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Throwback_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Seasonal_Type_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_D_N_D_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_College_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_C_M_R_A_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Simp_Addr_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Drop_Delivery_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Business_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Multi_Unit_Flag_ := 0;
    KEL.typ.int P_L___Curr_Addr_Is_Apt_Flag_ := 0;
    KEL.typ.str P_L___Addr_Hist_On_File_Flag_ := '';
    KEL.typ.int P_L___Addr_Emrg_Cnt3_M_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt6_M_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt2_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt3_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt5_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt10_Y_ := 0;
    KEL.typ.int P_L___Addr_Emrg_Cnt15_Y_ := 0;
    KEL.typ.nstr P_L___Best_Name_First_;
    KEL.typ.nstr P_L___Best_Name_Mid_;
    KEL.typ.nstr P_L___Best_Name_Last_;
    KEL.typ.nstr P_L___Best_S_S_N_;
    KEL.typ.nstr P_L___Best_D_O_B_;
    KEL.typ.nint P_L___Best_D_O_B_Age_;
    KEL.typ.int P_L___Prev_Addr_Is_Simp_Addr_Flag_ := 0;
    KEL.typ.int P_L___Prev_Addr_Is_Business_Flag_ := 0;
    KEL.typ.int P_L___Drg_Judg_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_L_T_D_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_L_T_D_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_L_T_D_Amt_Tot7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_L_T_D_New_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_L_T_D_Old_Dt7_Y_;
    KEL.typ.nstr P_L___Drg_L_T_D_Amt_List7_Y_;
    KEL.typ.nstr P_L___Drg_L_T_D_Dt_List7_Y_;
    KEL.typ.nint P_L___Drg_L_T_D_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_L_T_D_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Lien_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Suit_Cnt7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Suit_Amt_List7_Y_;
    KEL.typ.int P_L___Drg_Suit_Amt_Tot7_Y_ := 0;
    KEL.typ.nstr P_L___Drg_Suit_Dt_List7_Y_;
    KEL.typ.nint P_L___Drg_Suit_New_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_Suit_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Ln_J_Cnt7_Y_ := 0;
    KEL.typ.int P_L___Drg_Ln_J_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Drg_Ln_J_Amt_Tot7_Y_ := 0;
    KEL.typ.float P_L___Drg_Ln_J_Amt_Avg7_Y_ := 0.0;
    KEL.typ.nstr P_L___Drg_Ln_J_Amt_List7_Y_;
    KEL.typ.nstr P_L___Drg_Ln_J_Dt_List7_Y_;
    KEL.typ.nstr P_L___Drg_Ln_J_New_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Ln_J_New_Msnc7_Y_;
    KEL.typ.nstr P_L___Drg_Ln_J_Old_Dt7_Y_;
    KEL.typ.nint P_L___Drg_Ln_J_Old_Msnc7_Y_;
    KEL.typ.int P_L___Drg_Cnt7_Y_ := 0;
    KEL.typ.nint P_L___Drg_Old_Msnc7_Y_;
    KEL.typ.nint P_L___Drg_New_Msnc7_Y_;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Crim_List_Layout) Crim_List_;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Banko_List_Layout) Banko_List_;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_Ln_J7_Y_List_Layout) Ln_J7_Y_List_;
    KEL.typ.ndataset(Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout_L_T_D7_Y_List_Layout) L_T_D7_Y_List_;
    KEL.typ.str P_L___Edu_Rec_Flag_Ev_ := '';
    KEL.typ.nstr P_L___Edu_Src_List_Ev_;
    KEL.typ.str P_L___Edu_H_S_Rec_Flag_Ev_ := '';
    KEL.typ.str P_L___Edu_Coll_Rec_Flag_Ev_ := '';
    KEL.typ.nstr P_L___Edu_Coll_Src_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Src_Last_Dt_List_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Src_New_Rec_Old_Dt_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Src_New_Rec_New_Dt_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Src_New_Rec_Old_Msnc_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Src_New_Rec_New_Msnc_Ev_;
    KEL.typ.nstr P_L___Edu_Coll_Rec_Span_Ev_;
    KEL.typ.int P_L___Ast_Prop_Bus_Cnt_Ev_ := 0;
    KEL.typ.int P_L___Ast_Prop_Bus_Curr_Cnt_ := 0;
    KEL.typ.int P_L___Ast_Prop_Bus_Curr_W_Tax_Val_Cnt_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Bus_Curr_Tax_Val_List_;
    KEL.typ.int P_L___Ast_Prop_Bus_Curr_Tax_Val_Tot_ := 0;
    KEL.typ.int P_L___Util_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Util_Old_Dt_List_Ev_;
    KEL.typ.nstr P_L___Util_Old_Dt_Ev_;
    KEL.typ.nint P_L___Util_Old_Msnc_Ev_;
    KEL.typ.int P_L___Email_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Email_Flag_Ev_;
    KEL.typ.int P_L___Email_Free_Cnt_Ev_ := 0;
    KEL.typ.int P_L___Email_I_S_P_Cnt_Ev_ := 0;
    KEL.typ.int P_L___Email_Edu_Cnt_Ev_ := 0;
    KEL.typ.int P_L___Email_Corp_Cnt_Ev_ := 0;
    KEL.typ.int P_L___Ast_Prop_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_New_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Old_Dt_List_Ev_;
    KEL.typ.int P_L___Ast_Prop_Curr_Cnt_ := 0;
    KEL.typ.nint P_L___Ast_Prop_Flag_Ev_;
    KEL.typ.nint P_L___Ast_Prop_Curr_Flag_;
    KEL.typ.nint P_L___Ast_Prop_Ownership_Indx_;
    KEL.typ.int P_L___Ast_Prop_Curr_W_Mkt_Val_Cnt_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Curr_Mkt_Val_List_;
    KEL.typ.int P_L___Ast_Prop_Curr_W_Tax_Val_Cnt_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Curr_Tax_Val_List_;
    KEL.typ.int P_L___Ast_Prop_Curr_Tax_Val_Tot_ := 0;
    KEL.typ.int P_L___Ast_Prop_Curr_W_A_V_M_Val_Cnt_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Curr_A_V_M_Val_List_;
    KEL.typ.nint P_L___Ast_Prop_Curr_A_V_M_Val_Tot_;
    KEL.typ.nfloat P_L___Ast_Prop_Curr_A_V_M_Val_Avg_;
    KEL.typ.int P_L___Ast_Prop_Sale_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Sale_Amt_List_Ev_;
    KEL.typ.int P_L___Ast_Prop_Sale_Tot_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Sale_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Sale_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Sale_Old_Dt_Ev_;
    KEL.typ.nint P_L___Ast_Prop_Sale_New_Msnc_Ev_;
    KEL.typ.nint P_L___Ast_Prop_Sale_Old_Msnc_Ev_;
    KEL.typ.int P_L___Ast_Prop_Purch_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ast_Prop_Purch_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Purch_New_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Purch_Old_Dt_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Purch_New_Msnc_Ev_;
    KEL.typ.nstr P_L___Ast_Prop_Purch_Old_Msnc_Ev_;
    KEL.typ.int P_L___Ast_Prop_Purch_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Ast_Prop_Purch_Cnt5_Y_ := 0;
    KEL.typ.nint P_L___Srch_Coll_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Coll_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Coll_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Coll_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Coll_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Coll_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Credit_H_R_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Old_Msnc5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_New_Msnc5_Y_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Auto_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Auto_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Auto_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Auto_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Auto_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Auto_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Mtge_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Mtge_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Mtge_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Mtge_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Mtge_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Mtge_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Util_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Util_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Util_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Util_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Util_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Util_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Prepay_Card_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Coll_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Coll_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Coll_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Coll_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Coll_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Coll_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Credit_H_R_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Old_Msnc5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_New_Msnc5_Y__1_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Auto_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Auto_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Auto_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Auto_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Auto_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Auto_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Mtge_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Mtge_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Mtge_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Mtge_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Mtge_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Mtge_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Util_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Util_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Util_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Util_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Util_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Util_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Cnt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Dt_List5_Y__1_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_New_Dt5_Y__1_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Old_Dt5_Y__1_;
    KEL.typ.nint P_L___Srch_Prepay_Card_New_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Old_Msnc5_Y__1_;
    KEL.typ.nint P_L___Srch_Coll_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Coll_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Coll_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Coll_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Coll_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Coll_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Credit_H_R_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Credit_H_R_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Credit_H_R_Old_Msnc5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_New_Msnc5_Y__2_;
    KEL.typ.nstr P_L___Srch_Bank_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Auto_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Auto_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Auto_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Auto_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Auto_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Auto_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Mtge_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Mtge_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Mtge_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Mtge_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Mtge_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Mtge_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Util_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Util_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Util_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Util_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Util_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Util_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Cnt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Dt_List5_Y__2_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_New_Dt5_Y__2_;
    KEL.typ.nstr P_L___Srch_Prepay_Card_Old_Dt5_Y__2_;
    KEL.typ.nint P_L___Srch_Prepay_Card_New_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Prepay_Card_Old_Msnc5_Y__2_;
    KEL.typ.nint P_L___Srch_Comm_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Comm_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Comm_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Comm_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Comm_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Comm_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Stdnt_Loan_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Stdnt_Loan_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Stdnt_Loan_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Stdnt_Loan_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Stdnt_Loan_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Stdnt_Loan_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Pymt_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Retail_Pymt_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Retail_Pymt_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Retail_Pymt_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Pymt_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Pymt_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Quiz_Prov_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Quiz_Prov_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Quiz_Prov_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Quiz_Prov_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Quiz_Prov_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Quiz_Prov_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Retail_Dt_List5_Y_;
    KEL.typ.nint P_L___Srch_Retail_New_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Retail_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Retail_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Other_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Other_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_Other_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Other_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_Other_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Other_Old_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Cnt5_Y_;
    KEL.typ.nstr P_L___Srch_Dt_List5_Y_;
    KEL.typ.nstr P_L___Srch_New_Dt5_Y_;
    KEL.typ.nstr P_L___Srch_Old_Dt5_Y_;
    KEL.typ.nint P_L___Srch_New_Msnc5_Y_;
    KEL.typ.nint P_L___Srch_Old_Msnc5_Y_;
    KEL.typ.int P_L___Srch_Per_Lex_I_D_Cnt1_Y_ := 0;
    KEL.typ.nint P_L___Srch_S_S_N_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Addr_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_L_Name_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_F_Name_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Phone_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_D_O_B_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Email_Per_Lex_I_D_Cnt1_Y_;
    KEL.typ.int P_L___Srch_Per_Curr_Addr_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Srch_Lex_I_D_Per_Curr_Addr_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Srch_L_Name_Per_Curr_Addr_Cnt1_Y_ := 0;
    KEL.typ.int P_L___Srch_S_S_N_Per_Curr_Addr_Cnt1_Y_ := 0;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_F_L_S_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_A_S_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_S_D_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_P_S_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_F_L_A_S_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_F_L_P_S_Cnt1_Y_;
    KEL.typ.nint P_L___Srch_Per_Lex_I_D_W_Inp_F_L_A_P_S_Cnt1_Y_;
    KEL.typ.ntyp(E_Household().Typ) P_L___H_H_I_D_;
    KEL.typ.nint P_L___H_H_Mmbr_Cnt_;
    KEL.typ.nint P_L___H_H_Mmbr_Bureau_Only_Cnt_;
    KEL.typ.int P_L___H_H_Mmbr_Age18u_Cnt_ := 0;
    KEL.typ.nint P_L___Acc_Cnt_Ev_;
    KEL.typ.nstr P_L___Acc_Flag_Ev_;
    KEL.typ.nstr P_L___Acc_Dt_List_Ev_;
    KEL.typ.nstr P_L___Acc_New_Dt_Ev_;
    KEL.typ.nstr P_L___Acc_New_Msnc_Ev_;
    KEL.typ.nstr P_L___Acc_Dmg_Amt_List_Ev_;
    KEL.typ.int P_L___Acc_Dmg_Tot_Ev_ := 0;
    KEL.typ.nint P_L___Acc_New_Dmg_Amt_Ev_;
    KEL.typ.int P_L___Acc_Cnt1_Y_ := 0;
    KEL.typ.nint P_L___S_T_L_Cnt1_Y_;
    KEL.typ.nint P_L___S_T_L_Cnt2_Y_;
    KEL.typ.nint P_L___S_T_L_Cnt5_Y_;
    KEL.typ.nstr P_L___S_T_L_Dt_List5_Y_;
    KEL.typ.int P_L___Ver_Src_Cnt_Ev_ := 0;
    KEL.typ.nstr P_L___Ver_Src_List_Ev_;
    KEL.typ.nstr P_L___Ver_Src_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ver_Src_Last_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ver_Src_Old_Dt_Ev_;
    KEL.typ.nstr P_L___Ver_Src_New_Dt_Ev_;
    KEL.typ.str P___Lex_I_D_Rstd_Only_Flag_ := '';
    KEL.typ.nint P_L___Ver_Name_First_Src_Cnt_Ev_;
    KEL.typ.nstr P_L___Ver_Name_First_Src_List_Ev_;
    KEL.typ.nstr P_L___Ver_Name_First_Src_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ver_Name_First_Src_Last_Dt_List_Ev_;
    KEL.typ.nint P_L___Ver_Name_Last_Src_Cnt_Ev_;
    KEL.typ.nstr P_L___Ver_Name_Last_Src_List_Ev_;
    KEL.typ.nstr P_L___Ver_Name_Last_Src_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ver_Name_Last_Src_Last_Dt_List_Ev_;
    KEL.typ.nint P_L___Ver_S_S_N_Src_Cnt_Ev_;
    KEL.typ.nstr P_L___Ver_S_S_N_Src_List_Ev_;
    KEL.typ.nstr P_L___Ver_S_S_N_Src_Emrg_Dt_List_Ev_;
    KEL.typ.nstr P_L___Ver_S_S_N_Src_Last_Dt_List_Ev_;
    KEL.typ.nint P_L___Emrg_Age_;
    KEL.typ.epoch Archive___Date_ := 0;
    KEL.typ.epoch Date_First_Seen_ := 0;
    KEL.typ.epoch Date_Last_Seen_ := 0;
    KEL.typ.epoch Hybrid_Archive_Date_ := 0;
    KEL.typ.epoch Vault_Date_Last_Seen_ := 0;
    KEL.typ.int __RecordCount := 0;
  END;
  EXPORT Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Layout := RECORDOF(__UNWRAP(DATASET([],Non_F_C_R_A_Person_Attributes_V1_Dynamic_Res0_Internal_Layout)));
END;
